name: C_C++_CI
on:
  pull_request:
    branches:
      - master

jobs:
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@master
    with:
      dependencies: 'ninja gcc gcovr cmake openmpi'
      gcc-build: true
      clang-build: false
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}

  build-with-clang:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@master
    with: 
      dependencies: 'ninja clang gcovr cmake openmpi'
      gcc-build: false
      clang-build: true
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
